package peersim.core;

/**
 * Interface to identify protocols.
 * 用来标明协议的接口
 * @author Alberto Montresor
 * @version $Revision: 1.5 $
 */
public interface Protocol extends Cloneable {

    /**
     * Returns a clone of the protocol. It is important to pay attention to
     * implement this carefully because in peersim all nodes are generated by
     * cloning except a prototype node. That is, the constructor of protocols is
     * used only to construct the prototype. Initialization can be done
     * via {@link Control}s.
     */
    public Object clone();
}
